# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO=1.8
    - DJANGO=1.9

# selenium:
#before_install:
#    - "export DISPLAY=:99.0"
#    - "sh -e /etc/init.d/xvfb start"

install:
    - pip install --upgrade pip
    - pip install . --no-deps
    - pip install Django==$DJANGO.\* coveralls

script:
    - coverage run --source=django_tools ./setup.py test --verbosity=2

after_success:
    coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
