# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.5
sudo: false

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py27-django18
    - TOXENV=py27-django111
    - TOXENV=py34-django18
    - TOXENV=py34-django111
    - TOXENV=py35-django18
    - TOXENV=py35-django111

matrix:
  fast_finish: true

install:
    - pip install -r$TRAVIS_BUILD_DIR/requirements-test.txt

script:
    - pip freeze
    - travis_retry tox


