# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.5
sudo: false

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py34-django18
    - TOXENV=py34-django111
    - TOXENV=py35-django18
    - TOXENV=py35-django111

matrix:
  fast_finish: true

install:
    - pip install -r$TRAVIS_BUILD_DIR/requirements-test.txt

script:
    - pip freeze
    - travis_retry tox

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)

# work-around for https://github.com/travis-ci/travis-ci/issues/4794
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
